### ISSUE TITLE
Wrong configuration file noted in queue setup for tutorial

### ISSUE THREAD

**Issue by lschollmeyer** [perusworld/hornetq-jms-python#1]
Not an issue with the code per se, but in your instructions, where you set up the queue for your example, you note the vi hornetq-2.3.0.CR2/config/stand-alone/non-clustered/hornetq-configuration.xml path. This should be hornetq-jms.xml file.

**Comment by perusworld** [comment]
Awesome thank you, i have updated the docs

**Comment by lschollmeyer** [comment]
The tutorial and code snippets were helpful. By the way, do you have to
send the message in as a binary type? I had to modify the message to get it
to send. Odd!

Luke

**Comment by perusworld** [comment]
Not sure what you mean, if you want to send binary messages then you could use session.createBytesMessage() and then writeBytes to it and read the same on the other end. let me know if that helps.
